server.port= 9090
server.address=0.0.0.0
server.servlet.context-path=/api
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/eventsDB
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.image-directory=D:/projeto_integrador/eventoUfsm/eventosUfsm/src/main/resources/assets

#Linux
# scrapper.script.path=/home/marcelo/Documentos/eventoUfsm/scrapper_events_ufsm/src/scrape/getEvents.ts
# scrapper.working.dir=/home/marcelo/Documentos/eventoUfsm/scrapper_events_ufsm

#Windows:
scrapper.script.path= D:/projeto_integrador/eventoUfsm/scrapper_events_ufsm/src/scrape/getEvents.ts
scrapper.working.dir= D:/projeto_integrador/eventoUfsm/scrapper_events_ufsm